ams-view-logger/main/default/objects/amsvl_ViewLog__c/amsvl_ViewLog__c.object-meta.xml
<CustomObject>
    <description>Object for storing users&apos; view logs per related record.</description>
    <label>View Log</label>
    <nameField>
        <displayFormat>VL-{00000}</displayFormat>
        <label>View Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>View Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ams-view-logger/main/default/objects/amsvl_ViewLog__c/fields/amsvl_LastVisited__c.field-meta.xml
<CustomField>
    <fullName>amsvl_LastVisited__c</fullName>
    <description>Stores datetime when the user&apos;s view was logged.</description>
    <label>Last Visited</label>
    <type>DateTime</type>
</CustomField>

ams-view-logger/main/default/objects/amsvl_ViewLog__c/fields/amsvl_ObjectName__c.field-meta.xml
<CustomField>
    <fullName>amsvl_ObjectName__c</fullName>
    <description>Stores object name of related record.</description>
    <label>Object Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ams-view-logger/main/default/objects/amsvl_ViewLog__c/fields/amsvl_RecordId__c.field-meta.xml
<CustomField>
    <fullName>amsvl_RecordId__c</fullName>
    <description>Stores ID of related record.</description>
    <label>Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

ams-view-logger/main/default/objects/amsvl_ViewLog__c/fields/amsvl_User__c.field-meta.xml
<CustomField>
    <fullName>amsvl_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Stores ID of the user who viewed the record.</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>View_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

ams-view-logger/main/default/objects/amsvl_ViewLog__c/fields/amsvl_ViewCount__c.field-meta.xml
<CustomField>
    <fullName>amsvl_ViewCount__c</fullName>
    <description>Stores total view count of user per record.</description>
    <label>View Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ams-view-logger/main/default/classes/amsvl_CTR_LwcViewLogs.cls
public with sharing class amsvl_CTR_LwcViewLogs {
    @AuraEnabled
    public static Map<String,Integer> getViewLogsInfo(String recordId){
        Map<String,Integer> result = new Map<String,Integer>();

        String sObjName = Id.valueOf(recordId).getSObjectType().getDescribe().getName();
        
        //insert or update view logs
        updateViewLogs(recordId,sObjName);
        
        //query to get the Total Views Count and Total Viewers Count
        AggregateResult agxViewLogsInfo = amsvl_DAL_ViewLog.getViewCountByRecordId(recordId);
        result.put(
            'totalViewCount',
            Integer.valueOf(agxViewLogsInfo.get('totalViewCount'))
        );
        result.put(
            'totalViewerCount',
            Integer.valueOf(agxViewLogsInfo.get('totalViewerCount'))
        );
        
        return result;
    }

    private static void updateViewLogs(String recordId,String sObjName){
        Id userId = UserInfo.getUserId();
        Datetime lastVisited = Datetime.now();
        List<amsvl_ViewLog__c> viewLogs = amsvl_DAL_ViewLog.getViewLogsByUserAndRecordId(recordId,userId);
        List<amsvl_ViewLog__c> viewLogsToUpsert = new List<amsvl_ViewLog__c>();

        //insert new view log if new user
        if(viewLogs.isEmpty()){
            viewLogsToUpsert.add(new amsvl_ViewLog__c(
                amsvl_LastVisited__c = lastVisited,
                amsvl_ObjectName__c = sObjName,
                amsvl_RecordId__c = recordId,
                amsvl_User__c = userId,
                amsvl_ViewCount__c = 1
            ));
        }
        //update existing view log for user
        else{
            for(amsvl_ViewLog__c viewLog : viewLogs){
                viewLog.amsvl_LastVisited__c = lastVisited;
            	viewLog.amsvl_ViewCount__c += 1;
                viewLogsToUpsert.add(viewLog);
            }
        }

        Database.upsert(viewLogsToUpsert);
    }
}