ams-view-logger/main/default/objects/amsvl_ViewLog__c/amsvl_ViewLog__c.object-meta.xml
<CustomObject>
    <description>Object for storing users&apos; view logs per related record.</description>
    <label>View Log</label>
    <nameField>
        <displayFormat>VL-{00000}</displayFormat>
        <label>View Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>View Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ams-view-logger/main/default/objects/amsvl_ViewLog__c/fields/amsvl_LastVisited__c.field-meta.xml
<CustomField>
    <fullName>amsvl_LastVisited__c</fullName>
    <description>Stores datetime when the user&apos;s view was logged.</description>
    <label>Last Visited</label>
    <type>DateTime</type>
</CustomField>

ams-view-logger/main/default/objects/amsvl_ViewLog__c/fields/amsvl_ObjectName__c.field-meta.xml
<CustomField>
    <fullName>amsvl_ObjectName__c</fullName>
    <description>Stores object name of related record.</description>
    <label>Object Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ams-view-logger/main/default/objects/amsvl_ViewLog__c/fields/amsvl_RecordId__c.field-meta.xml
<CustomField>
    <fullName>amsvl_RecordId__c</fullName>
    <description>Stores ID of related record.</description>
    <label>Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

ams-view-logger/main/default/objects/amsvl_ViewLog__c/fields/amsvl_User__c.field-meta.xml
<CustomField>
    <fullName>amsvl_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Stores ID of the user who viewed the record.</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>View_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

ams-view-logger/main/default/objects/amsvl_ViewLog__c/fields/amsvl_ViewCount__c.field-meta.xml
<CustomField>
    <fullName>amsvl_ViewCount__c</fullName>
    <description>Stores total view count of user per record.</description>
    <label>View Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ams-view-logger/main/default/classes/amsvl_DAL_ViewLog.cls
 /**
 * @description Data service for View Log object
 * @author Angelika Galang
 * @since July 4, 2023
 */

 public inherited sharing class amsvl_DAL_ViewLog {

    //constants
        //public
    public static final String OBJECT_NAME = amsvl_ViewLog__c.SObjectType.getDescribe().getLocalName();
        //private
    private static final String OP_AND = 'AND';

    /**
     * @description
     *
     * @return  `List<String>`
     */
    private static List<String> getDefaultFields(){
        return new List<String>{
            amsvl_ViewLog__c.Id.getDescribe().getLocalName(),
            amsvl_ViewLog__c.amsvl_LastVisited__c.getDescribe().getLocalName(),
            amsvl_ViewLog__c.amsvl_ObjectName__c.getDescribe().getLocalName(),
            amsvl_ViewLog__c.amsvl_RecordId__c.getDescribe().getLocalName(),
            amsvl_ViewLog__c.amsvl_User__c.getDescribe().getLocalName(),
            'amsvl_User__r.Name',
            amsvl_ViewLog__c.amsvl_ViewCount__c.getDescribe().getLocalName()
        };
    }

    public static Integer getViewLogsCountByRecordId(String recordId){
        return Database.countQuery(
            ams_UTL_SearchStringBuilder.soqlSearch(
                new List<String>{
                    'count()'
                },
                OBJECT_NAME,
                'amsvl_RecordId__c =: recordId'
            )
        );
    }

    /**
     * @description 
     *
     * @param recordId 
     *
     * @return  `List<amsvl_ViewLog__c>`
     */
    public static List<amsvl_ViewLog__c> getViewLogsByRecordId(String recordId){
        return Database.query(
            ams_UTL_SearchStringBuilder.soqlSearch(
                getDefaultFields(),
                OBJECT_NAME,
                'amsvl_RecordId__c =: recordId'
            )
        );
    }

    /**
     * @description 
     *
     * @param recordId 
     *
     * @return  `List<amsvl_ViewLog__c>`
     */
    public static List<amsvl_ViewLog__c> getViewLogsByRecordId(
        String recordId,
        Integer limitSize,
        Integer offsetSize
    ){
        return Database.query(
            ams_UTL_SearchStringBuilder.soqlSearch(
                getDefaultFields(),
                OBJECT_NAME,
                'amsvl_RecordId__c =: recordId ORDER BY amsvl_LastVisited__c DESC LIMIT :limitSize OFFSET :offsetSize'
            )
        );
    }

    public static List<amsvl_ViewLog__c> getViewLogsByUserAndRecordId(
        String recordId,
        String userId
    ){
        return Database.query(
            ams_UTL_SearchStringBuilder.soqlSearch(
                getDefaultFields(),
                OBJECT_NAME,
                new List<String>{
                    'amsvl_RecordId__c =: recordId',
                    'amsvl_User__c =: userId'
                },
                OP_AND
            )
        );
    }

    /**
     * 
     * @param recordId 
     * @return  `AggregateResult`
     */
    public static AggregateResult getViewCountByRecordId(String recordId){
        return Database.query(
            ams_UTL_SearchStringBuilder.soqlSearch(
                new List<String>{
                    'SUM(amsvl_ViewCount__c) totalViewCount',
                    'COUNT(amsvl_User__c) totalViewerCount'
                },
                OBJECT_NAME,
                'amsvl_RecordId__c =: recordId GROUP BY amsvl_RecordId__c'
            )
        );
    }
}