ams-activity-datatable/main/default/objects/amsadt_ActivityTableCustomFilter__mdt/amsadt_ActivityTableCustomFilter__mdt.object-meta.xml
<CustomObject>
    <description>Setting up custom filters for activity table</description>
    <label>Activity Table Custom Filter</label>
    <pluralLabel>Activity Table Custom Filters</pluralLabel>
</CustomObject>

ams-activity-datatable/main/default/objects/amsadt_ActivityTableCustomFilter__mdt/fields/amsadt_ActivityTableSetting__c.field-meta.xml
<CustomField>
    <fullName>amsadt_ActivityTableSetting__c</fullName>
    <description>It is the related Activity table for an Activity Custom Filter</description>
    <label>ADT Activity Table Setting</label>
    <referenceTo>amsadt_ActivityTableSetting__mdt</referenceTo>
    <relationshipLabel>Activity Table Custom Filters</relationshipLabel>
    <relationshipName>Activity_Table_Custom_Filters</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

ams-activity-datatable/main/default/objects/amsadt_ActivityTableCustomFilter__mdt/fields/amsadt_FilterFieldName__c.field-meta.xml
<CustomField>
    <fullName>amsadt_FilterFieldName__c</fullName>
    <description>It is the field name in LWC</description>
    <label>Filter Field Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ams-activity-datatable/main/default/objects/amsadt_ActivityTableCustomFilter__mdt/fields/amsadt_FilterPlaceholder__c.field-meta.xml
<CustomField>
    <fullName>amsadt_FilterPlaceholder__c</fullName>
    <description>It is used in showing the Placeholder for custom filters</description>
    <label>Filter Placeholder</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ams-activity-datatable/main/default/objects/amsadt_ActivityTableCustomFilter__mdt/fields/amsadt_FilterSortOrder__c.field-meta.xml
<CustomField>
    <fullName>amsadt_FilterSortOrder__c</fullName>
    <description>It is to determine the ordering of custom filters to be shown in display</description>
    <label>Filter Sort Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ams-activity-datatable/main/default/objects/amsadt_ActivityTableCustomFilter__mdt/fields/amsadt_ObjectField__c.field-meta.xml
<CustomField>
    <fullName>amsadt_ObjectField__c</fullName>
    <description>It is the field in Activity object to be used in filter</description>
    <label>Object Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ams-activity-datatable/main/default/objects/amsadt_ActivityTableCustomFilter__mdt/fields/amsadt_ObjectFieldAlias__c.field-meta.xml
<CustomField>
    <fullName>amsadt_ObjectFieldAlias__c</fullName>
    <description>It is an alias used in query to determine in aggregate result</description>
    <label>Object Field Alias</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ams-activity-datatable/main/default/objects/amsadt_ActivityTableCustomFilter__mdt/fields/amsadt_ObjectFieldId__c.field-meta.xml
<CustomField>
    <fullName>amsadt_ObjectFieldId__c</fullName>
    <description>It is used if the query is using an ID as filter for example CreatedById</description>
    <label>Object Field Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ams-activity-datatable/main/default/objects/amsadt_ActivityTableSetting__mdt/amsadt_ActivityTableSetting__mdt.object-meta.xml
<CustomObject>
    <description>Setting containing object, fields, filters and other related settings in creation activity table</description>
    <label>ADT Activity Table Setting</label>
    <pluralLabel>ADT Activity Table Settings</pluralLabel>
</CustomObject>

ams-activity-datatable/main/default/objects/amsadt_ActivityTableSetting__mdt/fields/amsadt_DefaultFilterAllorMy__c.field-meta.xml
<CustomField>
    <fullName>amsadt_DefaultFilterAllorMy__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used for showing the All or My Filter in Activity Table</description>
    <inlineHelpText>Check if you want to show All or My Filter</inlineHelpText>
    <label>Default Filter: All or My</label>
    <type>Checkbox</type>
</CustomField>

ams-activity-datatable/main/default/objects/amsadt_ActivityTableSetting__mdt/fields/amsadt_DefaultFilterDateRange__c.field-meta.xml
<CustomField>
    <fullName>amsadt_DefaultFilterDateRange__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used for showing the Date Range filter in Activity Table</description>
    <inlineHelpText>Check if you want to show Date Range</inlineHelpText>
    <label>Default Filter: Date Range</label>
    <type>Checkbox</type>
</CustomField>

ams-activity-datatable/main/default/objects/amsadt_ActivityTableSetting__mdt/fields/amsadt_DefaultFilterDateRangeField__c.field-meta.xml
<CustomField>
    <fullName>amsadt_DefaultFilterDateRangeField__c</fullName>
    <description>Used for setting the field from object for Date Range filter</description>
    <inlineHelpText>Indicate the field from object for Date Range filter</inlineHelpText>
    <label>Default Filter: Date Range Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ams-activity-datatable/main/default/objects/amsadt_ActivityTableSetting__mdt/fields/amsadt_DefaultFilterDateRangeLabel__c.field-meta.xml
<CustomField>
    <fullName>amsadt_DefaultFilterDateRangeLabel__c</fullName>
    <description>Used for setting up the label for Date Range filter in Activity Table</description>
    <inlineHelpText>Indicate the label for Date Range filter</inlineHelpText>
    <label>Default Filter: Date Range Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ams-activity-datatable/main/default/objects/amsadt_ActivityTableSetting__mdt/fields/amsadt_DefaultFilterSortBy__c.field-meta.xml
<CustomField>
    <fullName>amsadt_DefaultFilterSortBy__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used for showing the Sort By Filter in Activity Table</description>
    <inlineHelpText>Check if you want to show Sort By filter</inlineHelpText>
    <label>Default Filter: Sort By</label>
    <type>Checkbox</type>
</CustomField>

ams-activity-datatable/main/default/objects/amsadt_ActivityTableSetting__mdt/fields/amsadt_DefaultFilterSortByField__c.field-meta.xml
<CustomField>
    <fullName>amsadt_DefaultFilterSortByField__c</fullName>
    <description>Used for setting the field from object for Sort By filter</description>
    <inlineHelpText>Indicate the field from object for Sort By filter</inlineHelpText>
    <label>Default Filter: Sort By Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ams-activity-datatable/main/default/objects/amsadt_ActivityTableSetting__mdt/fields/amsadt_DefaultFilterSortByLabel__c.field-meta.xml
<CustomField>
    <fullName>amsadt_DefaultFilterSortByLabel__c</fullName>
    <description>Used for setting up the label for Sort By filter in Activity Table</description>
    <inlineHelpText>Indicate the label for Sort By filter</inlineHelpText>
    <label>Default Filter: Sort By Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ams-activity-datatable/main/default/objects/amsadt_ActivityTableSetting__mdt/fields/amsadt_ObjectName__c.field-meta.xml
<CustomField>
    <fullName>amsadt_ObjectName__c</fullName>
    <description>It is the object name used in Activity Table (Event or Task)</description>
    <inlineHelpText>Determine if object used in Activity Table is either Event or Task</inlineHelpText>
    <label>Object Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

ams-activity-datatable/main/default/objects/amsadt_ActivityTableSetting__mdt/fields/amsadt_ParentObjectName__c.field-meta.xml
<CustomField>
    <fullName>amsadt_ParentObjectName__c</fullName>
    <description>The object name used where Activity is placed e.g. Account, Contact</description>
    <inlineHelpText>Determine if parent object in Activity Table is either Account, Contact etc</inlineHelpText>
    <label>Parent Object Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

ams-activity-datatable/main/default/objects/amsadt_ActivityTableSetting__mdt/fields/amsadt_QueryFields__c.field-meta.xml
<CustomField>
    <fullName>amsadt_QueryFields__c</fullName>
    <description>The fields being used from the Activity object for query</description>
    <inlineHelpText>Determine the fields in Activity object used for query</inlineHelpText>
    <label>Query Fields</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ams-activity-datatable/main/default/objects/amsadt_ActivityTableSetting__mdt/fields/amsadt_TableColumns__c.field-meta.xml
<CustomField>
    <fullName>amsadt_TableColumns__c</fullName>
    <description>This is the columns for Activity Table in JSON format e.g

{&quot;fieldName&quot;:&quot;Id&quot;, &quot;label&quot;: &quot;Subject&quot;, &quot;type&quot;: &quot;url&quot;,
&quot;typeAttributes&quot;: {
&quot;label&quot;: {
&quot;fieldName&quot;: &quot;Subject&quot;
}
}},
{&quot;fieldName&quot; : &quot;CreatedDate&quot;, &quot;label&quot; : &quot;Created Date&quot;, &quot;type&quot;: &quot;date-local&quot;, &quot;typeAttributes&quot;:{
&quot;month&quot;: &quot;2-digit&quot;,
&quot;day&quot;: &quot;2-digit&quot;
}},
{&quot;fieldName&quot; : &quot;CreatedBy.Name&quot;, &quot;label&quot; : &quot;Created By&quot;},</description>
    <inlineHelpText>indicate columns for Activity Table in JSON format</inlineHelpText>
    <label>Table Columns</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ams-activity-datatable/main/default/objects/amsadt_ActivityTableSetting__mdt/fields/amsadt_TableIcon__c.field-meta.xml
<CustomField>
    <fullName>amsadt_TableIcon__c</fullName>
    <description>It is used for determining the icon for the Activity Table. Check here https://www.lightningdesignsystem.com/icons/</description>
    <inlineHelpText>Indicate the icon to be used for Activity Table</inlineHelpText>
    <label>Table Icon</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

ams-activity-datatable/main/default/objects/amsadt_ActivityTableSetting__mdt/fields/amsadt_URLFields__c.field-meta.xml
<CustomField>
    <fullName>amsadt_URLFields__c</fullName>
    <description>This is to determine what fields or columns in Activity Table that have link in JSON format</description>
    <inlineHelpText>Indicate the columns or fields in Activity Table having links based on Table Columns field</inlineHelpText>
    <label>URL Fields</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ams-activity-datatable/main/default/classes/amsadt_DAL_ActivityTable.cls
 /**
 * @description Data service for Activity Table
 * @author Aldrin Vallespin
 * @since October 24, 2023
 */

 public inherited sharing class amsadt_DAL_ActivityTable {

    //constants
    //public
    public static final String OBJECT_ACTIVITY_SETTING_NAME = amsadt_ActivityTableSetting__mdt.SObjectType.getDescribe().getLocalName();
    public static final String OBJECT_ACTIVITY_FILTER_NAME = amsadt_ActivityTableCustomFilter__mdt.SObjectType.getDescribe().getLocalName();

    /**
     * @description
     *
     * @return  `List<String>`
     */
    private static List<String> getActivitySettingDefaultFields(){
        return new List<String>{
            amsadt_ActivityTableSetting__mdt.Id.getDescribe().getLocalName(),
            amsadt_ActivityTableSetting__mdt.DeveloperName.getDescribe().getLocalName(),
            amsadt_ActivityTableSetting__mdt.Label.getDescribe().getLocalName(),
            amsadt_ActivityTableSetting__mdt.amsadt_ObjectName__c.getDescribe().getLocalName(),
            amsadt_ActivityTableSetting__mdt.amsadt_QueryFields__c.getDescribe().getLocalName(),
            amsadt_ActivityTableSetting__mdt.amsadt_URLFields__c.getDescribe().getLocalName(),
            amsadt_ActivityTableSetting__mdt.amsadt_TableIcon__c.getDescribe().getLocalName(),
            amsadt_ActivityTableSetting__mdt.amsadt_TableColumns__c.getDescribe().getLocalName(),
            amsadt_ActivityTableSetting__mdt.amsadt_ParentObjectName__c.getDescribe().getLocalName(),
            amsadt_ActivityTableSetting__mdt.amsadt_DefaultFilterAllorMy__c.getDescribe().getLocalName(),
            amsadt_ActivityTableSetting__mdt.amsadt_DefaultFilterDateRange__c.getDescribe().getLocalName(),
            amsadt_ActivityTableSetting__mdt.amsadt_DefaultFilterSortBy__c.getDescribe().getLocalName(),
            amsadt_ActivityTableSetting__mdt.amsadt_DefaultFilterDateRangeField__c.getDescribe().getLocalName(),
            amsadt_ActivityTableSetting__mdt.amsadt_DefaultFilterSortByField__c.getDescribe().getLocalName(),
            amsadt_ActivityTableSetting__mdt.amsadt_DefaultFilterDateRangeLabel__c.getDescribe().getLocalName(),
            amsadt_ActivityTableSetting__mdt.amsadt_DefaultFilterSortByLabel__c.getDescribe().getLocalName()
        };
    }

    /**
     * @description
     *
     * @return  `List<String>`
     */
    private static List<String> getActivityFilterDefaultFields(){
        return new List<String>{
            amsadt_ActivityTableCustomFilter__mdt.Id.getDescribe().getLocalName(),
            amsadt_ActivityTableCustomFilter__mdt.DeveloperName.getDescribe().getLocalName(),
            amsadt_ActivityTableCustomFilter__mdt.Label.getDescribe().getLocalName(),
            amsadt_ActivityTableCustomFilter__mdt.amsadt_ActivityTableSetting__c.getDescribe().getLocalName(),
            amsadt_ActivityTableCustomFilter__mdt.amsadt_ObjectField__c.getDescribe().getLocalName(),
            amsadt_ActivityTableCustomFilter__mdt.amsadt_ObjectFieldId__c.getDescribe().getLocalName(),
            amsadt_ActivityTableCustomFilter__mdt.amsadt_FilterFieldName__c.getDescribe().getLocalName(),
            amsadt_ActivityTableCustomFilter__mdt.amsadt_FilterPlaceholder__c.getDescribe().getLocalName(),
            amsadt_ActivityTableCustomFilter__mdt.amsadt_ObjectFieldAlias__c.getDescribe().getLocalName(),
            amsadt_ActivityTableCustomFilter__mdt.amsadt_FilterSortOrder__c.getDescribe().getLocalName(),
            'amsadt_ActivityTableSetting__r.amsadt_ObjectName__c',
            'amsadt_ActivityTableSetting__r.amsadt_ParentObjectName__c',
            'amsadt_ActivityTableSetting__r.DeveloperName'
        };
    }

    /**
     * @description 
     *
     * @param activityAPIName 
     *
     * @return  `amsadt_ActivityTableSetting__mdt`
     */
    public static amsadt_ActivityTableSetting__mdt getActivitySettingsByAPIName(String activityAPIName){
        return Database.query(
            ams_UTL_SearchStringBuilder.soqlSearch(
                getActivitySettingDefaultFields(),
                OBJECT_ACTIVITY_SETTING_NAME,
                'DeveloperName =: activityAPIName'
            )
        );
    }

    /**
     * @description 
     *
     * @param activityAPIName 
     *
     * @return  `List<amsadt_ActivityTableCustomFilter__mdt>`
     */
    public static List<amsadt_ActivityTableCustomFilter__mdt> getActivityFilterList(String activityAPIName){
        return Database.query(
            ams_UTL_SearchStringBuilder.soqlSearch(
                getActivityFilterDefaultFields(),
                OBJECT_ACTIVITY_FILTER_NAME,
                'amsadt_ActivityTableSetting__r.DeveloperName =: activityAPIName'
            )
        );
    }

    /**
     * @description 
     *
     * @param activityAPIName 
     *
     * @return  `amsadt_ActivityTableCustomFilter__mdt`
     */
    public static amsadt_ActivityTableCustomFilter__mdt getActivityFilterByAPIName(String activityAPIName){
        return Database.query(
            ams_UTL_SearchStringBuilder.soqlSearch(
                getActivityFilterDefaultFields(),
                OBJECT_ACTIVITY_FILTER_NAME,
                'DeveloperName =: activityAPIName'
            )
        );
    }
}